- angular.json
- package.json
- projects/ngx-formentry/package.json
- projects/ngx-formentry/src/change-tracking/sample-form/sample-form.component.html
- projects/ngx-formentry/src/components/appointments-overview/appointments-overview.component.html
- projects/ngx-formentry/src/components/check-box/checkbox.component.html
- projects/ngx-formentry/src/components/input/input.directive.ts
- projects/ngx-formentry/src/components/input/label.component.ts
- projects/ngx-formentry/src/components/input/text-area.directive.ts
- projects/ngx-formentry/src/components/ngx-datetime-picker/ngx-datetime-picker.html
- projects/ngx-formentry/src/components/number-input/number-input.component.html
- projects/ngx-formentry/src/components/select/optgroup.directive.ts
- projects/ngx-formentry/src/components/select/option.directive.ts
- projects/ngx-formentry/src/components/select/select.component.spec.ts
- projects/ngx-formentry/src/components/select/select.component.ts
- projects/ngx-formentry/src/form-entry/error-renderer/error-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.css.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/styles/ngx-formentry.css
- src/app/app.component.html
- src/styles.css
- src/styles.scss
- yarn.lock
- Update the styling of form-entry to Carbon 11
*None.*
*None.*
*None.*
> (enhancement) bump styling to carbon 11 for form-entry engine

- angular.json
- projects/ngx-formentry/ng-package.json
Fixes a bunch of warnings when building and running the library by:
- Adding a map of external dependencies and their corresponding UMD module IDs to the package configuration.
- Adding a couple of libraries to the `allowedCommonJsDependencies` property of the Angular CLI builder.
> CommonJS dependencies warning
> External modules warning
> (chore) Fix warnings when building and running the library

- package.json
- projects/ngx-formentry/ng-package.prod.json
- projects/ngx-formentry/package.json
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
- projects/ngx-formentry/tsconfig.lib.prod.json
Fixes a bunch of issues that are currently preventing the library from getting published successfully. Specifically, this PR:
- Fixes a cyclic dependency between the `FormRenderer` and `ErrorRenderer` components.
- Changes the distribution format used when publishing the library to the [recommended](https://angular.io/guide/creating-libraries#publishing-libraries) Partial-Ivy mode.
Additionally, this PR also fixes a bunch of build warnings by adding a map of external dependencies and their corresponding UMD module IDs to the package configuration.
> (chore) Fix issues preventing successful publishing

- package.json
- projects/ngx-formentry/src/form-entry/form-entry.module.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
- projects/ngx-formentry/src/shared.module.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/mock/mock-translations.ts
- src/app/translate/translate.module.ts
- yarn.lock
- Add support for i18n translation in our forms
- Apply translation support on form labels and placeholder
- Add some mock translations
- For some reason, the labels are not getting translated, it could be because of the nesting that is involved to get labels @ibacher @FlorianRappl please advise on how to apply translations to labels like `Visit date` , `Provider` etc
[Ability to have arbitrary translations for labels in AMPATH forms](https://issues.openmrs.org/browse/O3-1325)
- Branched off this PR to add more work https://github.com/openmrs/openmrs-ngx-formentry/pull/4
> 03-1325: Ability to have arbitrary translations for labels in AMPATH forms.

- projects/ngx-formentry/src/form-entry/helpers/historical-expression-helper-service.ts
This is a companion for the PR on [patient chart](https://github.com/openmrs/openmrs-esm-patient-chart/pull/903) to allow the form engine to use values from previous observations not necessarily on the form.
This behaviour is opt-in. A question can register its concept to get the most recent value by setting the questionOption `useMostRecentValue` to `true` or `'true'`. Once that's done the most recent value for the concept associated with the question will be available in the historical data source under the pseudo-encounter "prevObs".
*None.*
*None.*
*None.*
> (feat) Support for an encounter of previous obs values

- README.md
Changes `npm` commands in the README to their `yarn` equivalents.
> (docs) Change npm commands to yarn equivalents

- projects/ngx-formentry/src/form-entry/directives/historical-value.directive.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
This PR restores the ability to use historical values from previous encounters when filling out form fields.
I inadvertently broke this feature in https://github.com/openmrs/openmrs-ngx-formentry/pull/13 when I attempted to rename the `HistoricalValueDirective`'s selector to a name containing our custom prefix (`ofeNode`) which ensured the linter stayed happy. Renaming this selector to anything other than `node` (to match the `node` Input of the `FormRenderer` component) completely breaks everything.
This PR changes the directive's `selector` name back to `[node]` and disables the `eslint/directive-selector` rule check.
Thanks to @enyachoke for reporting this regression on [Slack](https://openmrs.slack.com/archives/CHP5QAE5R/p1672993341776819). Apologies.
> Screenshot showing a historical …
> (fix) Restore the ability to use historical values

- projects/ngx-formentry/src/components/radio-button/radio.component.ts
- projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts
- src/app/app.component.ts
The PR adds a missing null check to the `extractObsValue` helper function. It also defaults the i18n to English
*None.*
*None.*
*None.*
> Fix extractObsValue helper and remove console.log in radio button

- projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts
This PR adds a Null check for the raw encounter since the primary use case here https://github.com/openmrs/openmrs-esm-patient-chart/blob/316fe80b69911ecee8267d2fe08a74f76e145cc2/packages/esm-form-entry-app/src/app/form-creation/form-creation.service.ts#L116 could register a `undefined` data source 
*None.*
*None.*
> (fix) Add null check for undefined rawPrevObs

- projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.spec.ts
- projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts
…
Rename and change the behaviour of the helper extractObsValue.
```
Takes a target control, an encounter and concept uuid. If the target control has a value it returns it
otherwise it tries to find it in the encounter. Finally, it returns null of it can't find either of them.
```
*None.*
*None.*
*None.*
> (fix) rename the helper extractObsValue to getObsFromControlOrEncounter and change behaviour

- projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts
- src/app/app.component.ts
- Checking if all 5 values to be passed to the CVD risk calculation else return null
- The screenshot below shows the logs that came out of testing when all values are not passed.
- `hasValues` returns `undefined` and the `CVD function` returns `null`
- https://issues.openmrs.org/browse/KH-62
> (fix):CVD risk calculation should return null if some value is not passed.[KH-62]

- projects/ngx-formentry/src/components/number-input/number-input.component.html
- projects/ngx-formentry/src/components/number-input/number-input.module.ts
- projects/ngx-formentry/src/components/number-input/number.directive.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.css
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.css.ts
- projects/ngx-formentry/styles/ngx-formentry.css
- src/assets/carbon.select.theme.css
-This adds functionality to disable scroll on `NumberInput` this is as a result of users complaining that the form is changing values as you scroll to view additional fields.
-UI enhancement to remove excessive margin and try to make the form look compact.
*None.*
*None.*
> enhancement: Add Number Input directive and UI enhancement

- projects/ngx-formentry/src/components/number-input/number-input.component.ts
At the moment when you try to increment a number where the min and max schema values haven't been set, the form engine doesn't increment the value. This PR adds ability to fix this edge case error. It also adds ability to start `inCrement` and `Decrement` on the set `max` and `min` values as defined from the schema.
> (fix) fix `onIncrement` and `onDecrement` on number input when `max` and `min` value are absent

- projects/ngx-formentry/src/components/radio-button/radio.component.ts
- projects/ngx-formentry/src/form-entry/directives/historical-value.directive.ts
This pull request addresses an issue with the `Use Value` button in the `RadioButtonControlComponent`. Previously, when the `Use Value` button was clicked, it displayed the UUID of the previous value inserted, which was not user-friendly.
In this fix, I updated the `RadioButtonControlComponent` to display the label of the previous value instead of the UUID. This change enhances the usability of the component, making it easier for users to understand and interact with the form.
Before:
Now:
Thanks,
> (fix) Display label concept instead of uuid when use previous value  on radio buttons

- README.md
- projects/ngx-formentry/src/components/ngx-remote-select/ngx-remote-select.component.ts
- projects/ngx-formentry/src/components/ngx-remote-select/remote-select.component.html
- projects/ngx-formentry/styles/ngx-formentry.css
- This PR fixes `ng-select` which is inside a `remote-select` and displays the dropdown panel above all content.
- Before(Ngx-Formentry)
- Dev3(Patient chart)
- Fixed(Ngx-Formentry)
- Fixed by this PR(Patient chart)
- https://issues.openmrs.org/browse/KH-143
- After merging this we need to test it in the patient chart forms and see if it actually works.
> (fix) KH-141: Remote Select dropdown at the end of the form content should display above all content.

- projects/ngx-formentry/src/components/check-box/checkbox.component.ts
When editing an encounter, if there were observations saved using checkboxes within the form, the previously selected values were not appearing as checked. The observations were being saved correctly, the issue was that when opening the form, checkbox values were always reset to an empty array.
> (fix) Fixed issue where checkboxes would lose pre-selected values upon form loading

- projects/ngx-formentry/src/form-entry/validators/max.validator.ts
- projects/ngx-formentry/src/form-entry/validators/min.validator.ts
This PR fixes the min and max validators for number inputs to validate value 0.
This is tested out on form-entry-app.
https://issues.openmrs.org/browse/KH-180
> (fix) KH-180: Fixed the min and max validator for number inputs to validate value 0

- projects/ngx-formentry/src/adult.json
- projects/ngx-formentry/src/form-entry/form-entry.module.ts
- projects/ngx-formentry/src/form-entry/value-adapters/patient-identifier.adapater.spec.ts
- projects/ngx-formentry/src/form-entry/value-adapters/patient-identifier.adapter.spec.ts
- projects/ngx-formentry/src/form-entry/value-adapters/patient-identifier.adapter.ts
- projects/ngx-formentry/src/lib/index.ts
- src/app/app.component.ts
This PR adds ability to generate patient identifiers. In addition it also adds ability to populate fields with type `patientIdentifer` with existing identifiers.
https://thepalladiumgroup.atlassian.net/browse/KHP3-3708
> (feat) KHP3-3708 Add adapter in form engine to handle creating patient identifiers

- projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.ts
This merge request is intended to resolve the issue with form saving. Currently, no form on the website can be saved because the encounterType is not being set in the request. While addressing this problem, I discovered that there is also an issue with encounterDatetime. This field is not being added as well, but these changes should rectify it.
Additionally, I found a problem where active visits, which are automatically created during application deployment, cannot work correctly with this date. When starting a visit manually, the date is set correctly, and everything starts working.
https://issues.openmrs.org/browse/O3-2312
Should be merged with: https://github.com/openmrs/openmrs-esm-patient-chart/pull/1314
> (fix) Default to using the current date

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
This PR fixes the incomplete dropdown overlay for multi select dropdowns
None
> Multi select dropdown panel should come above the form end

- projects/ngx-formentry/src/form-entry/value-adapters/patient-identifier.adapter.spec.ts
This PR contains the development done here: https://github.com/openmrs/openmrs-ngx-formentry/pull/42 with tests fixed.
This pull request adds support for translating error messages and labels within a form. Labels are now provided by a JSON file, following the naming convention "<lang>.json". This update provides a more user-friendly experience for non-native speakers.
Currently, the form supports English and French languages, and in the future, additional languages can be added by creating a new JSON file with the appropriate naming convention.
In addition to updating the form to display translated labels, this pull request also updates some core components, including buttons and error messages, to be translatable. The updated tests ensure that the translation module is properly imported …
> i18n - Add TranslateModule to testBed

- .github/workflows/main.yml
Fixes two slightly changed commands from Yarn upgrade
> (chore) Update CI pre-release and release scripts

- .github/workflows/main.yml
This PR updates GitHub workflow to publish the dist. folder assets.
> (fix) publish assets from the correct folder

- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis-helper.ts
- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.ts
- projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.ts
- src/app/adult-1.6.json
This PR adds support to create diagnosis by specifying `rank` `certainty` coded diagnosis`. In a follow up PR will add support for non-coded diagnosis.
> (feat) Update diagnosis to support `rank` and `certainty`

- projects/ngx-formentry/src/abstract-controls-extension/afe-form-control.ts
- projects/ngx-formentry/src/abstract-controls-extension/afe-form-group.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
- src/app/adult-1.6.json
This PR updates the alert feature to show when a certain expression is meet without relying on the control-relations to evaluate
> (enhc) Update alert feature to show when an expression evaluates

- projects/ngx-formentry/src/components/check-box/checkbox.component.html
- projects/ngx-formentry/src/components/check-box/checkbox.component.ts
- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- src/app/adult-1.6.json
When `disableWhenExpression` evaluates to true, all other checkbox options are now greyed out. Additionally, any previously selected options are automatically deselected. This functionality is particularly useful in scenarios where selecting an option like none means other options should not be concurrently selected.
https://thepalladiumgroup.atlassian.net/browse/KHP3-4179
> (KHP3-4179) Grey out all other options on checkbox when hideExpression is true

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
This PR fixes an issue with the width of form labels in the workspace exceeding the size of the viewport. The [text-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap) CSS property applied to the label tag doesn't work on either Firefox or Safari. I've replaced all occurrences of `text-wrap: wrap` with [overflow-wrap: break-word](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap), which is compatible with all evergreen browsers. 
https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/971ee128-f908-42e7-94eb-4c577aca241d
Slack thread where the issue was first reported https://openmrs.slack.com/archives/CHP5QAE5R/p1697450994041169.
*None*
> (fix) Width of form labels shouldn't exceed workspace width

- projects/ngx-formentry/styles/picker.min.css
This PR fixes a display issue with the DatePicker on tablet devices due to a higher z-index value on its parent container. Additionally, it removes the scrollbar to enhance the user experience by preventing flickering. Below GIF shows the fix and the error
> (fix) Fix overlay stacking context so Datepicker isn't hidden on tablet

- projects/ngx-formentry/src/components/workspace-launcher/workspace-launcher.component.html
- projects/ngx-formentry/src/components/workspace-launcher/workspace-launcher.component.ts
- projects/ngx-formentry/src/components/workspace-launcher/workspace-launcher.module.ts
- projects/ngx-formentry/src/form-entry/form-entry.module.ts
- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
- projects/ngx-formentry/src/form-entry/question-models/index.ts
- projects/ngx-formentry/src/form-entry/question-models/interfaces/workspace-launcher-options.ts
- projects/ngx-formentry/src/form-entry/question-models/workspace-launcher.model.ts
This creates a new question type that renders a button that opens whatever workspace is configured.
https://github.com/openmrs/openmrs-ngx-formentry/assets/1031876/4e99bf91-1608-4b8f-8d58-6506d0210f49
https://issues.openmrs.org/browse/O3-2510
**Depends on https://github.com/openmrs/openmrs-esm-patient-chart/pull/1430**
> (feat) O3-2510: Should be able to launch Add Drug Order workspace from a form

- projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.html
- projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
- src/app/adult-1.6.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
This PR contains a number of enhancements, namely add ability to scroll to the top of a section in the event the form contains long sections. Moved the `Save` and `Close` buttons to the side navigation to improve usability on tablet devices.
https://github.com/openmrs/openmrs-ngx-formentry/assets/28008754/5e8c0da6-e16a-40ad-b56f-f2ae5647e21c
> (feat) O3-2531: Enhance form control sizing for improved UX in tablet mode

- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.spec.ts
- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.ts
- projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.spec.ts
Reviewed encounter payload regarding diagnosis:
- Don't send diagnosis within encounter payload in case no diagnosis were changed
- Resolved the issue with the payload when deleting a diagnosis
- Ensured proper handling of newly added and modified diagnoses while constructing the encounter payload
- Reviewed unit tests to align with backend's expected diagnosis payload format
> (fix) Better handling of diagnoses

- projects/ngx-formentry/styles/ngx-formentry.css
- src/assets/carbon.select.theme.css
Lengthy dropdown option text should be wrapped in multiple lines
> (enhancement) Lengthy dropdown option text should be wrapped in multiple lines

- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.ts
Resolved an issue during encounter editing where the generated payload incorrectly marked existing diagnoses as voided, despite intending to retain them. With this fix, only the diagnoses explicitly removed by the user will be marked as voided in the payload as expected.
This issue had minimal impact as an HTTP 400 error would occur due to an unrelated [problem](https://talk.openmrs.org/t/rest-module-and-multi-valued-attributes/40898) in the OpenMRS core, preventing the editing of existing diagnoses.
> (fix) Resolved issue with incorrect voided diagnosis in generated payload

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
I've fixed an issue with the placement of the dropdown element when using `ng-select` elements in the form engine. More specifically, the `ng-select` element gets used when the chosen rendering type for a field is [multiCheckbox](https://github.com/openmrs/openmrs-ngx-formentry/blob/c33c107a53e58ca20dec015da5fb3d76edbbe630/projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts#L273). In the `ng-select` [configuration](https://www.npmjs.com/package/@ng-select/ng-select#api), you can choose to provide a string value to the `appendTo` input. `appendTo` allows you to append the dropdown to the body of your document or any other element using a CSS selector. 
Presently, the dropdown's `appendTo` input is set to `form`, which means the dropdown gets appended to the form element. …
> (fix) Fix ng-select dropdown position

- src/styles.scss
This PR resolves the issue of missing styling in the Form Preview (what you see when you run a dev server using `yarn start`) which caused the DatePicker component and other elements to appear incorrectly. 
To fix this, I've added the necessary styles as imports to the global `styles.scss` stylesheet. Additionally, I've tested my changes against the dev3 reference application to ensure that styling isn't broken in the Clinical Forms workspace (see the attached video below).
> Before (broken styles for the DatePicker)
https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/347f0ba1-3bf7-404d-91e5-55038a850971
> After (fixed styles)
https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/7cb0b776-d36e-46d0-998d-9672d0c7c884
> Verification that the Clinical Forms workspace is …
> (fix) Fix date picker styles in Form Entry preview

- projects/ngx-formentry/src/components/radio-button/radio.component.spec.ts
This PR adds unit tests for the `RadioButtonControlComponent` that gets rendered when the rendering type for a field is `radio`.
*None*
*None*
*None*
> (test) Add unit tests for RadioButtonControlComponent

- projects/ngx-formentry/src/components/ngx-datetime-picker/ngx-datetime-picker.component.ts
- projects/ngx-formentry/src/components/ngx-datetime-picker/ngx-datetime-picker.html
The DatePicker component accepts a `datePickerType` prop whose value gets funnelled down to the [NgDatePicker](https://danielykpan.github.io/date-time-picker/) component under the hood. This prop accepts one of [three](https://github.com/DanielYKPan/date-time-picker/blob/5ccf6be2d24c6e074709881d64dd9116c3b6aa14/projects/picker/src/lib/date-time/date-time.class.ts#L17) possible values: 
- `both` which renders both a calendar and a timer
- `calendar` which renders a calendar
- `timer` which renders a timer
Presently, the input placeholder is set to just show `mm/dd/yyyy` for all three cases. This PR amends the placeholder so an appropriate value is shown in each case. 
> Both
> Timer
> Calendar
> (feat) Make datepicker placeholder aware of datePickerFormat input

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
This PR tweaks the navigation pattern introduced in #119 so that navigation links are only shown for forms with multiple pages.
> (feat) Only show navigation buttons on multi-page forms

- projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.scss
- projects/ngx-formentry/src/components/ngx-tabset/components/tab.component.css
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
This PR contains fixes to newly added navigation section:
- translation for prev / next page
- added title/popup with page name on button hover
- correct alignment for RTL
- horizontal scrolling / oveflow
[Video](https://monosnap.com/file/Fn6kAFyIwLh2HKYPADbTkNrSLwLyEQ)
[O3-2870](https://openmrs.atlassian.net/browse/O3-2870)
> (fix) O3-2870: Form navigation fixes

- projects/ngx-formentry/src/components/radio-button/radio.component.html
- projects/ngx-formentry/src/components/radio-button/radio.component.ts
- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.ts
This PR adds `readOnly` property on radio button to make it disabled to meet some specification.
> (feat) Enable readonly radio buttons

- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
- projects/ngx-formentry/src/form-entry/question-models/decimal-validation.model.ts
This PR adds a rendering type to the Form Engine based off of work on [this commit](https://github.com/AMPATH/ngx-openmrs-formentry/pull/125)t from the original repository. It introduces a decimal rendering type along with its validators and its associated model
https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/983567ba-a6fb-4e83-81d3-e30296b1550f
> (feat) Add decimal rendering type

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
- src/translations/en.json
- src/translations/fr.json
- src/translations/km.json
This PR fixes the Orders UI display in clinical forms. Specifically, it targets the following UI inconsistencies:
- The dividers don't look right - they should not have a bottom border, and they're using the wrong colour.
- There's inconsistent spacing across the elements in the section.
- It's not immediately obvious that the text `ORD-701` represents the `Blood urea nitrogen` lab order's unique order number.
- Styling for the order number `div` is rendered regardless of whether an order number exists.
- Elements are spaced out further
- Consistent styling for dividers
- An identifying label for the order number
> (fix) Fix lab orders UI in clinical forms

- projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.spec.ts
- projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts
Issue: [https://openmrs.atlassian.net/browse/O3-2872](https://openmrs.atlassian.net/browse/O3-2872)
On the O3, while editing a question inside of an ObsGroup only the edited questions are saved, voiding the other questions inside of the same ObsGroup. 
This happens because the request only sends the questions that have been changed and the core will void the existing ObsGroup with all the existing questions to create a new one with the questions that came from the request.
In addiction, if an ObsGroup is empty (with all questions voided) it will void the existing ObsGroup and create a new empty one, which doesn't make sense.
1 - Create a form with an ObsGroup
2 - Edit the `ObsGroup` and you will notice that only the edit concept is there.
Request:
```
{
...
"obs":[
{
"groupMembers":[
{ …
```
> (fix) O3-2872: Fix inconsistent data when editing obsGroups in an encounter

- projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
In this pull request, I've made modifications to the navigation buttons within the form. Currently, the buttons have a "header-like" styling, leading to an oversized font. To enhance consistency across sections and text elements, I've realigned the button style to match that of other components.
Before:
After:
Thanks,
> (feat) Enhancement on navigation button style

- .eslintrc.json
- .prettierignore
- .yarnrc.yml
- README.md
- package.json
- projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts
- yarn.lock
Our current setup is running Prettier as a part of ESLint. These are two separate concerns that should be handled separately by different tools.
This PR removes [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) from our linting config as recommended [here](https://prettier.io/docs/en/integrating-with-linters.html#notes) and [here](https://www.joshuakgoldberg.com/blog/you-probably-dont-need-eslint-config-prettier-or-eslint-plugin-prettier/). I've also separated ESLint concerns from Prettier so that ESLint doesn't handle both. The recommended modern approach treats Prettier and ESLint as separate unrelated tools.
I've also removed the `prettier` script from the root-level package.json to the `lint-staged` config so that `lint-staged` runs Prettier after ESLint.
> (chore) Separate linting and formatting concerns

- angular.json
This PR tweaks the Angular CLI configuration for the `serve` script to automatically launch the default web browser when `ng serve` is executed.
> (chore) Launch browser automatically on `ng serve`

- README.md
- projects/ngx-formentry/package.json
This PR bumps the Angular form engine library version to the latest minor release, v5.1.0. #138 only bumped the Angular app that consumes the library. I've added some notes to the README that hopefully makes the distinction clear and guides the next person cutting the release so they don't miss this.
> (chore) Reapply v5.1.0 version bump

- projects/ngx-formentry/src/components/ngx-remote-select/ngx-remote-select.component.ts
- projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
- projects/ngx-formentry/src/form-entry/question-models/interfaces/data-source.ts
- projects/ngx-formentry/src/form-entry/question-models/interfaces/remote-select-question-options.ts
- projects/ngx-formentry/src/form-entry/question-models/question-base.ts
- projects/ngx-formentry/src/form-entry/question-models/remote-select-question.ts
- src/app/adult-1.6.json
- src/app/app.component.ts
- src/app/app.module.ts
- yarn.lock
Implements two changes:
1. Updates `dataSources` schema to align with [o3 format](https://github.com/openmrs/openmrs-contrib-json-schemas/blob/36ea64ac4c18a94719ddc380679cca9a6e3cf910/form.schema.json#L574) while maintaining backwards compatibility
2. Adds support for remote-select question type control
```json
{
"id": "admitToLocation",
"type": "obs",
"required": true,
"label": "Admit to location",
"questionOptions": {
"rendering": "remote-select",
"required": true,
"concept": "CIEL:169403",
"datasource": {
"name": "location_datasource",
"config": {
"tag": "Admission Location"
}
}
}
}
```
> (feat) Add remote-select question type and migrate data sources to o3 schema format
