openmrs/openmrs-ngx-formentry

package.json
projects/ngx-formentry/src/form-entry/form-factory/form-node.ts
projects/ngx-formentry/src/form-entry/form-factory/form.factory.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/question-models/question-base.ts
projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.ts
projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts
src/app/adult-1.6.json
src/app/app.component.ts
src/app/mock/obs.json
yarn.lock

This PR introduces support for ordering repeating groups and multi selects. It will use `form_namespace_and_path` to maintain the order in which question were answered. when rendering the form for editing.
Payload sent to server including `formFieldNamespace,formFieldPath`
Recieved from server including `formFieldNamespace,formFieldPath`
*None.*
*None.*

Introduce support for maintaining question order when rendering

---

.github/workflows/main.yml
package.json
projects/ngx-formentry/karma.conf.js
projects/ngx-formentry/src/change-tracking/sample-form/sample-form.component.ts
projects/ngx-formentry/src/components/afe-ng-select.component.ts
projects/ngx-formentry/src/components/input/label.component.spec.ts
projects/ngx-formentry/src/components/ngx-pick-datetime/lib/date-time/calendar.component.spec.ts
projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.ts
projects/ngx-formentry/src/components/select/select.component.spec.ts
projects/ngx-formentry/src/form-entry/control-hiders-disablers/disabler-helper.ts
projects/ngx-formentry/src/form-entry/data-sources/data-sources.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.spec.ts
projects/ngx-formentry/src/form-entry/services/debug-mode.service.spec.ts
projects/ngx-formentry/src/form-entry/services/form-schema-compiler.service.spec.ts
projects/ngx-formentry/src/form-entry/services/form-schema-compiler.service.ts
projects/ngx-formentry/src/form-entry/services/historical-encounter-data.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.ts
projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts
projects/ngx-formentry/src/form-entry/value-adapters/obs.adapter.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/order.adapter.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/order.adapter.ts
src/app/app.component.ts
src/karma.conf.js
src/main.ts

This PR:
- Fixes existing tests.
- Switches to `ChromeHeadless` as the default browser environment for test execution and sets some reasonable karma configuration options.
- Adds a test step to the CI process.
- Configures the test script to run in the pre-push hook.
- Gets rid of some `console.log` statements.

(test) Fix existing tests and add `test` job to CI process

---

projects/ngx-formentry/src/components/radio-button/radio.component.html
projects/ngx-formentry/src/components/radio-button/radio.component.ts
projects/ngx-formentry/src/components/radio-button/radio.module.ts
projects/ngx-formentry/src/form-entry/form-entry.module.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/interfaces/base-options.ts
projects/ngx-formentry/src/form-entry/question-models/interfaces/radio-button-options.ts
projects/ngx-formentry/src/form-entry/question-models/models.ts
projects/ngx-formentry/src/form-entry/question-models/question-base.ts
projects/ngx-formentry/src/form-entry/question-models/radio-button.model.ts

- Radio buttons should be unelectable
- This should  be an optional setting
- Radio buttons cannot be unselected by default

Allow radio buttons to be unselectable

---

.github/workflows/main.yml
.gitignore
package.json
turbo.json
yarn.lock

[Turborepo](https://turborepo.org/docs) is a high-performance build system for JavaScript and TypeScript codebases. Turborepo provides superfast incremental builds with zero runtime overhead. Turbo was previously only available for monorepos. This is no longer the case, with version 1.6 ushering in support for all JavaScript and TypeScript repositories.
This PR adds `turbo` to this repository and configures scripts in our lockfile and CI workflows to leverage it.

(chore) Add Turborepo

---

projects/ngx-formentry/src/components/radio-button/radio.component.html
projects/ngx-formentry/src/components/radio-button/radio.component.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/interfaces/base-options.ts
projects/ngx-formentry/src/form-entry/question-models/interfaces/radio-button-options.ts
projects/ngx-formentry/src/form-entry/question-models/question-base.ts
projects/ngx-formentry/src/form-entry/question-models/radio-button.model.ts

* name is now properly a bound property so it changes per radio group
* allowUnselect works in a sane way and defaults to off
* fixed some potential styling issues
*None.*
*None.*
*None.*

Various fixes to the radio buttons

---

projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/interfaces/select-question-options.ts
projects/ngx-formentry/src/form-entry/question-models/multi-select-question.ts
projects/ngx-formentry/src/form-entry/question-models/select-question.ts

Restores labels for the multiselect component
*None.*
[O3-1740](https://issues.openmrs.org/browse/O3-1740)
*None.*

(fix) Restore proper labels for multiselect component (O3-1740)

---

src/app/app.component.ts

Changes the `currentLanguage` back to English from Khmer, which I assume was only set for testing purposes.

(feat) Change current language back to `en`.

---

projects/ngx-formentry/src/components/check-box/checkbox.component.ts

This PR fixes an issue with the `checkbox` component where selecting an option would not update the checkbox's `selected` array. This PR updates the logic that handles updating the selected array appropriately each time an option is selected.

(fix) Update question values based on a checkbox's selected answers

---

projects/ngx-formentry/src/components/radio-button/radio.component.css
projects/ngx-formentry/src/components/radio-button/radio.component.html
projects/ngx-formentry/src/components/radio-button/radio.component.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html

Allow radio questions do be displayed horizontally via configuration. If no orientation configuration is provided, original behaviour is kept.

(feat) Allow inline horizontal radio buttons via cfg

---

projects/ngx-formentry/src/components/radio-button/radio.component.ts

Fixed radio component not updating when it's value modification is triggered by another component

(fix) Update radio selected option on value modification

---

projects/ngx-formentry/src/form-entry/form-factory/validation.factory.ts

(fix) Show correct `maxLengthValidator` error when a value exceeds the maximum length

---

projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts

Removes an extraneous `textarea` case statement.

(fix) Remove repeated case statement for the `textarea` rendering type

---

angular.json
projects/ngx-formentry/src/adult.json
projects/ngx-formentry/src/form-entry/form-entry.module.ts
projects/ngx-formentry/src/form-entry/form-factory/form.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/diagnosis-question.ts
projects/ngx-formentry/src/form-entry/question-models/interfaces/diagnosis-question-options.ts
projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/diagnosis.adapter.ts
projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/encounter.adapter.ts
projects/ngx-formentry/src/mock/diagnoses.json
projects/ngx-formentry/src/mock/orders.json
src/app/adult-1.6.json
src/app/app.component.ts
yarn.lock

Add support for diagnoses.
*Code exemple
```
{
"label": "Primary Diagnoses",
"sections": [
{
"label": "Primary Diagnoses",
"isExpanded": "true",
"questions": [
{
"label": "Primary Diagnosis",
"id": "primaryDiagnosisId",
"type": "diagnosis",
"questionOptions": {
"rendering": "repeating",
"dataSource": "diagnoses",
"rank": 1
}
}
]
}
]
},
{
"label": "Secondary Diagnoses",
"sections": [
{
"label": "Secondary Diagnoses",
"isExpanded": "true",
"questions": [
{
"label": "Secondary Diagnosis",
"id": "secondaryDiagnosisId",
"type": "diagnosis",
"questionOptions": {
"rendering": "repeating",
"dataSource": "diagnoses",
"rank": 2
}
}
]
}
]
}
```
*None.*
*None.*

(feat) Add support for Diagnoses to form engine

---

projects/ngx-formentry/src/components/number-input/number-input.component.html
projects/ngx-formentry/src/components/number-input/number-input.component.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-factory/validation.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/max-length-validation.model.ts
projects/ngx-formentry/src/form-entry/question-models/max-validation.model.ts
projects/ngx-formentry/src/form-entry/question-models/min-length-validation.model.ts
projects/ngx-formentry/src/form-entry/question-models/min-validation.model.ts
projects/ngx-formentry/src/form-entry/validators/max-length.validator.ts
projects/ngx-formentry/src/form-entry/validators/min-length.validator.ts

This PR adds max and min length validation for [text](https://ampath-forms.vercel.app/docs/field-types-reference#text) and [number](https://ampath-forms.vercel.app/docs/field-types-reference#number) input fields. 
https://www.loom.com/share/722f2d9f997a4a4da7a4305232fa8475

(feat): Add max and min length validation for number input

---

package.json
projects/ngx-formentry/package.json

(chore) Release v3.1.0

---

projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.spec.ts
projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts

Add ability to evaluate if string matches regular expression
Sample schema : 
{
"type": "patientIdentifier",
"label": "Recency Id",
"questionInfo": "",
"id": "recencyId",
"required": "false",
"default": "",
"questionOptions": {
"rendering": "text",
"identifierType": "fd52829a-75d2-4732-8e43-4bff8e5b4f1a"
},
"validators": [
{
"type": "js_expression",
"failsWhenExpression": "doesNotMatchExpression('^REC\\\\d{5}-\\\\d{5,6}$', recencyId)",
"message": "Please provide the correct format for the recency id ie. REC+mflCode+number eg.REC11902-00062"
}
]
}

(feat) Add ability to evaluate if string matches regular expression

---

projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.spec.ts
projects/ngx-formentry/src/form-entry/helpers/js-expression-helper.ts

Add calculate gravida expression helper

(feat) Add calculate gravida expression helper

---

package.json

This PR cuts a new `minor` release of Form entry, `v3.2.0`.
Form entry `3.2.0` contains several new features and improvements.
We’ve added a new `calcGravida` helper function for computing gravida, which is the number of times a woman has been pregnant, regardless of whether these pregnancies were carried to term. 
`3.2.0` also adds a new expression helper that checks whether a provided string value matches a certain regular expression. This helper can then be used to show an error message when the values do not match.
We’ve added an adapter to the form engine that handles the creation of identifiers in the form submission payload. This adapter also handles populating `patientIdentifier` type fields with existing identifiers.
We’ve added the ability to reset fields when a field further …

(chore) Release `v3.2.0`

---

projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts

Reviewed form field path generation to include question identifier.

(fix) Form field path should use questionId since this is unique per form

---

projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts

(feat) Load observations based on form path

---

projects/ngx-formentry/src/components/input/text-area.directive.ts
projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.html
projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.scss
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.css
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.scss
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.ts
yarn.lock

Updated styles since update to core carbon styles.
Designs https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/61f03e914d1575a2cec45453

(enhc) Update form-entry styling post carbon-styles upgrade

---

.vscode/settings.json
README.md

Updates the README file for this repo with the intention of providing more up to date content and cleaning up cruft.
*None*
*None*
*None*

(docs) Update README

---

projects/ngx-formentry/src/components/ngx-datetime-picker/ngx-datetime-picker.css
projects/ngx-formentry/src/components/ngx-tabset/components/ngx-tab-set.component.scss

This PR addresses two primary concerns:
- Resolves the scrolling issue experienced in the previous PR.
- Ensures that the Weeklist Control renders correctly, as there were instances where it wasn't displaying as expected
https://github.com/openmrs/openmrs-ngx-formentry/assets/28008754/9e054ffc-2a04-4f54-ae66-4bafc20cfa8c
https://github.com/openmrs/openmrs-ngx-formentry/assets/28008754/015677fd-55c2-48d3-ae6f-7ee94f51ab35

(feat) O3-2531: Fix date-time week list and improve scrollToView

---

projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
src/app/adult-1.6.json

The question type workspace-launcher was not bootstrapped for hide and show expressions.  The PR addresses the issue.

(feat) Bootstrap hide functionality for workspace launcher

---

package.json
turbo.json

This PR adds the `prettier` task to the turbo config, making it possible to cache its output. Similarly, it amends various tasks run by Git hooks so they can also leverage turbo.
*None*
*None*

(chore) Cache various tasks using turbo

---

package.json

Cuts a new major release of Form Entry, v5.0.0.

(chore) Release v5.0.0

---

src/app/app.component.spec.ts
src/app/app.component.ts
src/app/translate/json-loader.ts

This PR improves tests for the App component so that they more closely resemble how the user uses the Form Entry app. 
*None*
*None*
*None*

(test) Improve AppComponent tests

---

projects/ngx-formentry/src/components/check-box/checkbox.component.spec.ts

This PR adds unit tests for the `CheckboxControlComponent` that gets rendered when the rendering type for a field is `checkbox`.
*None*
*None*
*None*

(test) Add unit tests for CheckboxControlComponent

---

projects/ngx-formentry/src/components/number-input/number-input.component.spec.ts

This PR adds unit tests for the `NumberInput` component.
*None*
*None*
*None*

(test) Add unit tests for NumberInputComponent

---

projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html

(feat) Added support for translations on form navigation links labels

---

projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.spec.ts
projects/ngx-formentry/src/form-entry/value-adapters/obs-adapter-helper.ts

[](https://openmrs.atlassian.net/browse/O3-2872)

(Fix) O3-2872: Fixed multiselect in obsgroup

---

projects/ngx-formentry/src/form-entry/value-adapters/patient-identifier.adapter.ts

This PR filters out hidden questions when generating patient identifiers.

(fix) Remove hidden fields from patient identifier question types

---

README.md
package.json

This PR cuts a new minor release of Ngx Formentry. It also updates the README with release steps (specific to Yarn v1, which is what were using here) and some improvements to the Contributing section.

(chore) Release v5.1.0

---

projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts

Handle changes in Population Type Concepts

Handle changes in Population Type Concepts

---

projects/ngx-formentry/src/components/machine-learning-button/machine-learning.component.ts
projects/ngx-formentry/src/components/machine-learning-button/machine-learning.service.ts

This is to fix HTS Eligibility Screening form validation where some fields had not been validated

fix HTS eligibility form validation for various fields

---

projects/ngx-formentry/src/components/machine-learning-button/machine-learning.component.ts
projects/ngx-formentry/src/components/machine-learning-button/machine-learning.service.ts
projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts
src/app/adult-1.8.json

Fix issues introduced by change in HTS Eligibility Screening form

Fix issues introduced by change in HTS Eligibility Screening form

---

projects/ngx-formentry/src/components/machine-learning-button/machine-learning.component.ts
projects/ngx-formentry/src/components/machine-learning-button/machine-learning.service.ts
projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts
src/app/app.component.ts

Fixed form validations for children below 18years. Fixed Population Type concepts

Fixed form validations for children below 18years. Fixed Population Type concepts

---

projects/ngx-formentry/src/components/machine-learning-button/concepts.ts
projects/ngx-formentry/src/components/machine-learning-button/machine-learning.component.ts
projects/ngx-formentry/src/components/machine-learning-button/machine-learning.service.ts
projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts
src/app/app.component.ts

More fixes due to change in HTS Eligibility screening form concepts V2

More fixes due to change in HTS Eligibility screening form concepts V2

---

projects/ngx-formentry/src/components/machine-learning-button/concepts.ts
projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts

added new logic to screened for TB

added new logic to screened for TB

---

projects/ngx-formentry/src/components/machine-learning-button/machine-learning.component.ts
projects/ngx-formentry/src/components/machine-learning-button/model-helper.ts

Fixed the auto generated risk score function on the eligibility screening form change in concepts

Fixed the auto generated risk score function on the eligibility screening form change in concepts

---

package.json
projects/ngx-formentry/package.json

This PR cuts a new major release of the Angular Form Engine with a breaking change following an Angular version upgrade (from v16 to v17). Note that the proposed version number is v17.x.x to align with the Angular library ecosystem convention of aligning version numbers with the Angular version.

(chore) Release v17.0.0

---

projects/ngx-formentry/src/components/workspace-launcher/workspace-launcher.component.ts
projects/ngx-formentry/src/form-entry/form-factory/question.factory.ts
projects/ngx-formentry/src/form-entry/form-renderer/form-renderer.component.html
projects/ngx-formentry/src/form-entry/question-models/interfaces/workspace-launcher-options.ts
projects/ngx-formentry/src/form-entry/question-models/workspace-launcher.model.ts

This PR updates **workspaceLauncher** to work correctly since the functionality was moved to _@openmrs/esm-framework_ this pr adjusts it to work well.

(fix) Resolve failing workspace launcher

---

package.json

This PR is to publish a major release of this repository. The reason for the major release is a breaking change introduced in #160.
This release includes following changes:
⚠️ Breaking Changes:
(BREAKING): Resolve failing workspace launcher #160 by @donaldkibet

(chore) Release v19.0.0
